//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        public Pracownicy()
        {
            this.Rozmowies = new HashSet<Rozmowy>();
            this.Dzialies = new HashSet<Dzialy>();
            this.Stanowiskas = new HashSet<Stanowiska>();
        }
    
        public int idP { get; set; }
        public string imieP { get; set; }
        public string nazwiskoP { get; set; }
        public string miastoP { get; set; }
        public string adresP { get; set; }
        public string nrTelP { get; set; }
        public Nullable<double> placaP { get; set; }
    
        public virtual ICollection<Rozmowy> Rozmowies { get; set; }
        public virtual ICollection<Dzialy> Dzialies { get; set; }
        public virtual ICollection<Stanowiska> Stanowiskas { get; set; }
    }
}
