//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozmowy
    {
        public Rozmowy()
        {
            this.Podanias = new HashSet<Podania>();
        }
    
        public int idR { get; set; }
        public int idP { get; set; }
        public int idPo { get; set; }
        public Nullable<System.DateTime> dataRozmowy { get; set; }
    
        public virtual ICollection<Podania> Podanias { get; set; }
        public virtual Podania Podania { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
