//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanowiska
    {
        public Stanowiska()
        {
            this.stan_dzial = new HashSet<stan_dzial>();
            this.Pracownicies = new HashSet<Pracownicy>();
        }
    
        public int idS { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<stan_dzial> stan_dzial { get; set; }
        public virtual ICollection<Pracownicy> Pracownicies { get; set; }
    }
}
